---
- name: ensure autossh is installed
  apt: pkg=autossh state=latest update_cache=true
  notify:
  
- name: Copy autossh services to systemd.
  template:
    src: templates/autossh.sh.j2
    dest: "{{ autossh_systemd_dir }}/autossh-{{ item.id | lower | regex_replace('\\s+', '-') | regex_replace('[^a-z0-9-]', '') }}.service"
    mode: 0644
  with_items: "{{ autossh_connections }}"
  register: autossh_systemd_service

- name: Reload systemctl.
  command: systemctl daemon-reload
  when: autossh_systemd_service.changed

- name: Enable autossh services.
  service: name={{ item.dest | basename }} enabled=true state=restarted
  when: autossh_systemd_service.changed and item.dest is defined
  with_items: "{{ autossh_systemd_service.results }}"
